include::header_internal.adoc[]
include::public.adoc[]
== Application settings

=== Profiles setting
Production profile:

[source,java,linenums,options="nowrap"]
----
include::../../main/resources/application.properties[]
----

== Code conventions and best practices

----
We are using google styleguide settings for IDE. <1>
This allows to share the same formatting code accross developers machines/IDEs.
----
----
For CodeBase we are using Oracle naming guidelines states. De-facto and De-ure industry standard. <2>
Mysql Error codes <3>
----
=== Packages

NOTE:  Package names are written in all lower case to avoid conflict with the names of classes or interfaces.
Companies use their reversed Internet domain name to begin their package names.
[source,java,linenums]
----
    ua.org.smartjava.domain.speaker
    ua.org.smartjava.domain.topic
----

=== Constants
NOTE:  The names of variables declared class constants and of ANSI constants should be all uppercase with words separated by underscores ("_").
[source,java,linenums]
----
    public static final String HAL_JSON_CHARSET_UTF_8 = "application/hal+json;charset=UTF-8";

    private static final String SPRING_HATEOAS_OBJECT_MAPPER = "_halObjectMapper";
----

=== Methods
NOTE:  Methods should be verbs, in mixed case with the first letter lowercase, with the first letter of each internal word capitalized.

[source,java,linenums]
----
public Speaker create(Speaker speaker) {
        ...
    }

Optional<Speaker> findByName(String name);

public Speaker createSpeaker() {
        return Speaker.builder().name(name).build();
    }
----

=== Methods in Tests
CAUTION:  Methods name should start with prefix *test* followed by testing method name in *CamelCase*.
If there are more than one branch for testing, than use underscore _ and describe *testCase* with the *first letter lowercase*.
Method name pattern is:     *test<MethodName>_<testCase>*

method to test:
[source,java,linenums]
----
    public Topic getTopic(long topicId) {
        ...
    }
----
methods in tests for *getTestCase(long testCaseId)* explicitly by their name describe possible scenarios.
[source,java,linenums]
----
    @Test
    public void testGetTopic_success() {
        ...
    }

    @Test
    public void testGetTopic_notFound() {
        ...
    }
----
//TODO Add given/when/then
=== Special notes
WARNING:  If you need to format string, do not use `java.text.MessageFormat` since its behavior depends on locale.
  relies on the system Locale. Use `org.slf4j.helpers.MessageFormatter` instead.


=== Database
==== Tables
NOTE: Tables naming describes entities in plural form. The underscores are used
between word, only lower case letters are used. For example:
```
topic
speaker
```
==== Constraints, Keys, Indexes
NOTE: For indexes, foreign keys use uppercase latters to describe type of construction
 and column name with underscores that construction is applied to:

```
CONSTRAINT `FK_table_name`

KEY `FK_table_name`

UNIQUE KEY `UK_table_name`
```

==== Applying a patch

==== JPA mapping entity

IMPORTANT: Do not edit/delete files in db.migration folder. In this case the checksum is changed.
Updates to DB schema are applied only by adding new patch.

== Links

<1> Google StyleGuide for IDE. https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml

<2> Oracle naming guidelines. http://www.oracle.com/technetwork/java/codeconventions-150003.pdf
http://www.oracle.com/technetwork/java/codeconvtoc-136057.html

<3> Mysql error codes. https://dev.mysql.com/doc/refman/5.5/en/error-messages-server.html