== "Ditaa" extentions example

:imagesdir: images

=== Lets create DB schema

[ditaa, "Speaker database table"]
....
    +----------+
    | tableName|
    +----------+
    | id       |
    | name     |
    | topic    |
    |          |
    +----------+
....
=== Relation between Tables
[ditaa, "Relation"]
....
    +----------+
    | table1   |
    +----------+ 1
    | id       |<---+
    | name     |    |
    | topic    |    |
    |          |    |
    +----------+    |   +----------+
                    |   | table2   |
                    |   +----------+
                    | * | id       |
                    +-->| FK_table1|
                        | topic    |
                        |          |
                        +----------+
....
=== Process diagram
[ditaa, "asciidoctor-diagram-process"]
....
                   +-------------+
                   | Asciidoctor |-------+
                   |   diagram   |       |
                   +-------------+       | PNG out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        |---+ Asciidoctor +--->|               |
 |  Text  |   +-------------+    |   Beautiful   |
 |Document|   |   !magic!   |    |    Output     |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
....
=== Edge
[ditaa, "edge"]
....
+---------+
| cBLU    |
|  text   |
|    +----+
|    |cPNK|
|    |    |
+----+----+
....
=== Colors in primitive blocks
This is example of creating the primitive blocks with
specifying the fill color code.

[ditaa, color]
....
/----\ /----\
|c33F| |cC02|
|    | |    |
\----/ \----/

/----\ /----\
|c1FF| |c1AB|
|    | |    |
\----/ \----/
....

=== Color Codes
Also we can specify the color on text format or in hex.
[ditaa, color codes]
....
/-------------+-------------\
|cRED RED     |cBLU BLU     |
+-------------+-------------+
|cGRE GRE     |cPNK PNK     |
+-------------+-------------+
|cBLK BLK     |cYEL YEL     |
\-------------+-------------/
....

=== Tags
Tags can change the figure display format.
[ditaa, Tags]
....
+-----+
|{d}  |
|     |
|     |
+-----+

+-----+
|{s}  |
|     |
|     |
+-----+

+-----+
|{io} |
|     |
|     |
+-----+
....

=== Lines
Adding : we are creating the break-line.
[ditaa, lines]
....
----+  /----\  +----+
    :  |    |  :    |
    |  |    |  |{s} |
    v  \-=--+  +----+
....

=== Points market
'*' creates point markers
[ditaa, Point markers]
....
*----*
|    |      /--*
*    *      |
|    |  -*--/
*----*
....

=== Text handling
[ditaa, Text handling]
....
/-----------------\
| Things to do    |
| cGRE            |
| o Cut the grass |
| o Buy jam       |
| o Fix car       |
| o Make website  |
\-----------------/
....

== "Plantuml" extentions examples

=== Class hierarchy diagram
[plantuml, diagram-classes, png]
....
class ResultActions
class MvcResult
class MockHttpServletResponse
class MockHttpServletRequest

ResultActions <|-- MvcResult
MvcResult <|-- MockHttpServletResponse
MvcResult <|-- MockHttpServletRequest
....

=== Component diagram
[plantuml,"demo",png]
--
artifact ".adoc-File" as adoc
artifact ".html-File" as html
artifact ".pdf-File" as pdf
artifact ".epub-File" as epub3
component asciidoctor
adoc -> asciidoctor
asciidoctor -down-> html
asciidoctor -down-> pdf
asciidoctor -down-> epub3
--

=== Interface and classes
[plantuml, abstract-list-example, png]
....
interface BaseInterface
interface ChildInterface
class FirstImpl
class SecondImpl

BaseInterface <|-- ChildInterface
ChildInterface <|.. FirstImpl
ChildInterface <|.. SecondImpl
....

=== Auth flow diagram
[plantuml, sequence-example, png]
....
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response
Bob -> AuthServer: validate&auth user
AuthServer --> Bob: generated Token

Bob -> Microservice1: restAPI call
Microservice1 --> Bob: resource response

Microservice1 -> Microservice2
Microservice2 --> Microservice1

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
....

=== Components interaction
[plantuml, "component-overview", png]
....
component "HTTP Server" as server
component "HTTP Client" as client
component "Java Application" as app

client -> HTTP : use
HTTP - server
server - servlet.api

app --> servlet.api : use
....